-- Sistema Bahia - schema minimo para rodar no Supabase/Lovable.
-- Rode este arquivo no SQL Editor do Supabase quando o projeto estiver vazio.
-- Login inicial: usuario admin / senha admin123.

create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nome text,
  usuario text unique,
  email text,
  senha_hash text,
  perfil text,
  senha_temporaria boolean default false,
  trocar_senha_obrigatorio boolean default false,
  acesso_pendente boolean default false,
  data_solicitacao text,
  ativo boolean default true
);

create table if not exists entidades (
  id bigint generated by default as identity primary key,
  entidade text,
  cnpj text,
  responsavel text,
  email_responsavel text,
  telefone text,
  endereco text,
  territorio_identidade text,
  municipio_entidade text,
  certificacao text,
  licenca_ambiental text,
  caa text,
  can text,
  atep text,
  agente_negocio text,
  numero_convenio text,
  an_atep_ateg text,
  nome_ateg text,
  coordenador_tipo text,
  nome_coordenador text,
  natureza_juridica text,
  dap_caf text,
  tipologia_beneficiarios text,
  comunidade_tradicional text,
  ativa_dinamica text,
  area text,
  status_qualificacao text default 'Cadastro inicial',
  nivel text,
  pontuacao integer default 0,
  pontuacao_q1 integer default 0,
  pontuacao_q2 integer default 0,
  data_cadastro text,
  cadastrado_por text,
  cadastrado_por_email text,
  ativo boolean default true
);

create table if not exists cursos (
  id bigint generated by default as identity primary key,
  curso text,
  area text,
  nivel text,
  campo_link text,
  id_questionario text,
  questionario text,
  status_mapeamento text,
  descricao text,
  carga_horaria text,
  owner_email text,
  estoque_total integer default 0,
  ativo boolean default true
);

create table if not exists perguntas_qualificacao (
  id bigint generated by default as identity primary key,
  questionario text,
  ordem integer,
  pergunta text,
  opcao_1 text,
  opcao_2 text,
  opcao_3 text,
  pontos_1 integer default 0,
  pontos_2 integer default 5,
  pontos_3 integer default 10,
  pontos_sim integer default 1,
  ativo boolean default true
);

create table if not exists perguntas_bpf (
  id bigint generated by default as identity primary key,
  secao text,
  subsecao text,
  codigo_pergunta text,
  ordem integer,
  pergunta text,
  tipo_resposta text,
  opcoes text default 'S;N;P;NA',
  pontos_sim integer default 1,
  ativo boolean default true
);

create table if not exists perguntas_curso (
  id bigint generated by default as identity primary key,
  curso_id bigint,
  id_pergunta text,
  id_questionario text,
  questionario text,
  ordem integer,
  pergunta text,
  pontos_sim integer default 1,
  ativo boolean default true
);

create table if not exists alternativas_curso (
  id bigint generated by default as identity primary key,
  pergunta_id bigint,
  id_alternativa text,
  id_pergunta text,
  id_questionario text,
  ordem integer,
  alternativa text,
  pontos integer default 0,
  ativo boolean default true
);

create table if not exists protocolos (
  id bigint generated by default as identity primary key,
  protocolo text unique,
  entidade_id bigint,
  curso_id bigint,
  area text,
  pontuacao_curso integer default 0,
  status text,
  etapa_atual text,
  responsavel_atual text,
  solicitante_nome text,
  solicitante_email text,
  data_abertura text,
  data_atualizacao text,
  data_agendada text,
  observacao text,
  os_modelo_nome text,
  os_modelo_path text,
  os_preenchida_nome text,
  os_preenchida_path text,
  os_preenchida_em text,
  os_preenchida_por text,
  ativo boolean default true
);

create table if not exists respostas_entidade (
  id bigint generated by default as identity primary key,
  entidade_id bigint,
  questionario text,
  pergunta_id bigint,
  pergunta text,
  resposta text,
  pontuacao integer,
  data_resposta text
);

create table if not exists respostas_bpf (
  id bigint generated by default as identity primary key,
  entidade_id bigint,
  pergunta_id bigint,
  pergunta text,
  resposta text,
  pontuacao integer,
  data_resposta text
);

create table if not exists respostas_curso (
  id bigint generated by default as identity primary key,
  protocolo text,
  pergunta_id bigint,
  pergunta text,
  resposta text,
  pontuacao integer,
  data_resposta text
);

create table if not exists owners_area (
  id bigint generated by default as identity primary key,
  area text,
  etapa text,
  nome text,
  email text,
  usuario text,
  ativo boolean default true
);

create table if not exists historico_fluxo (
  id bigint generated by default as identity primary key,
  protocolo text,
  status_anterior text,
  status_novo text,
  usuario text,
  data_movimento text,
  observacao text
);

create table if not exists notificacoes (
  id bigint generated by default as identity primary key,
  protocolo text,
  destinatario text,
  assunto text,
  corpo text,
  enviado integer default 0,
  data_criacao text,
  data_envio text,
  erro text
);

create table if not exists importacoes_sistema (
  id bigint generated by default as identity primary key,
  chave text unique,
  arquivo text,
  hash_arquivo text,
  data_atualizacao text
);

insert into usuarios (nome, usuario, email, senha_hash, perfil, ativo, acesso_pendente)
values ('Administrador', 'admin', '', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Administrador', true, false)
on conflict (usuario) do update
set senha_hash = excluded.senha_hash,
    perfil = excluded.perfil,
    ativo = true,
    acesso_pendente = false;

create index if not exists idx_usuarios_login on usuarios (usuario, email, ativo);
create index if not exists idx_entidades_status_ativo on entidades (status_qualificacao, ativo);
create index if not exists idx_protocolos_status on protocolos (status);
create index if not exists idx_historico_protocolo on historico_fluxo (protocolo);

alter table usuarios drop constraint if exists usuarios_perfil_check;
alter table usuarios add constraint usuarios_perfil_check
check (
  perfil is null or perfil in (
    'Administrador',
    'Moderador',
    'Analista Administrativo',
    'Analista Tecnico',
    'Agendamento',
    'Execucao'
  )
);

alter table usuarios disable row level security;
alter table entidades disable row level security;
alter table cursos disable row level security;
alter table perguntas_qualificacao disable row level security;
alter table perguntas_bpf disable row level security;
alter table perguntas_curso disable row level security;
alter table alternativas_curso disable row level security;
alter table protocolos disable row level security;
alter table respostas_entidade disable row level security;
alter table respostas_bpf disable row level security;
alter table respostas_curso disable row level security;
alter table owners_area disable row level security;
alter table historico_fluxo disable row level security;
alter table notificacoes disable row level security;

